services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: banco
    restart: always
    volumes:
      - banco-data:/var/lib/postgresql/data
    
  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db


volumes:
  banco-data: